# GroupBy

In [7]:
import pandas as pd
import numpy as np

In [52]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5)*10,
                   'data2' : np.random.randn(5)*14})

In [53]:
df

  key1 key2      data1      data2
0    a  one  17.231548  -3.389084
1    a  two   6.869134   5.951653
2    b  one   6.520152  -6.453391
3    b  two   2.279103  15.265651
4    a  one  15.089004  10.341398

In [54]:
grouped = df['data1'].groupby(df['key1'])

In [55]:
grouped

In [56]:
grouped.sum()

key1
a    39.189686
b     8.799254
Name: data1, dtype: float64

# MultiIndex

In [57]:
means = df['data1'].groupby([df['key1'], df['key2']]).mean()

In [58]:
means

key1  key2
a     one     16.160276
      two      6.869134
b     one      6.520152
      two      2.279103
Name: data1, dtype: float64

In [37]:
means.unstack()

key2        one       two
key1
a      3.937708  0.025303
b     13.182257  0.439742